name: Build & Deploy Docker App

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: rizkyoktamara/cicd

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Check Docker
        run: |
          docker version
          docker info

      - name: Network check Docker Hub
        run: |
          curl -I https://registry-1.docker.io/v2/
          curl -I https://auth.docker.io/token

      # - name: Verify secrets exist
      #   run: |
      #     if [ -z "$DOCKERHUB_USERNAME" ]; then echo "USERNAME EMPTY"; else echo "USERNAME OK"; fi
      #     if [ -z "$DOCKERHUB_TOKEN" ]; then echo "TOKEN EMPTY"; else echo "TOKEN OK"; fi
      #   env:
      #     DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      #     DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Build Docker image
      #   run: |
      #     docker build -t $IMAGE_NAME:latest .

      # - name: Push Docker image
      #   run: |
      #     docker push $IMAGE_NAME:latest
