name: Build & Deploy Docker App

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]

env:
  IMAGE_NAME: rizkyoktamara/cicd
  CONTAINER_NAME: service-backend-1
  REGISTRY: docker.io

jobs:
  build-and-push:
    runs-on: [self-hosted, ubuntu-latest]

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker image
      run: docker build -t $REGISTRY/${{ env.IMAGE_NAME }}:latest .

    - name: Push image to DockerHub
      run: docker push $REGISTRY/${{ env.IMAGE_NAME }}:latest

    - name: Create SSH key file
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.VM_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: SSH Deploy to VM
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} << 'EOF'
          echo "Logging into DockerHub..."
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

          echo "Pulling latest image..."
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/cicd-githubnew:latest

          echo "Stopping & removing old container..."
          docker stop service-backend-1 || true
          docker rm service-backend-1 || true

          echo "Running new container..."
          docker run -d --name service-backend-1 -p 4000:4000 ${{ secrets.DOCKERHUB_USERNAME }}/cicd-githubnew:latest
        EOF


